<a href="https://colab.research.google.com/github/KyleFranzR/CPE-313/blob/main/Rodriguez_Hands-on-Activity-8.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activity 5.1 Text Similarity

#### Objective(s):

This activity aims to introduce how to implement text similarity

#### Intended Learning Outcomes (ILOs):
* Demonstrate how to remove special characters from text
* Demonstrate how to measure text simiarity using distance
* Demonstrate how to find text similarity using Count Vector and TF-IDF Vectorizer

#### Resources:
* Jupyter Notebook
* songdata.csv

## Procedures
Load the necessary libraries

In [ ]:
import nltk
import pandas as pd

In [ ]:
data = pd.read_csv('songdata.csv')
data.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

Find the lyrics by the artist The Beatles

In [ ]:
beatles = data[data.artist=='The Beatles']
beatles.head()

,artist,song,link,text
1198,The Beatles,A Shot Of Rhythm And Blues,/b/beatles/a+shot+of+rhythm+blues_20014867.html,"Well, if your hands start a-clappin' \r\nAnd ..."
1199,The Beatles,Across The Universe,/b/beatles/across+the+universe_10026507.html,Words are flowing out like \r\nEndless rain i...
1200,The Beatles,All I've Got To Do,/b/beatles/all+ive+got+to+do_10026646.html,"Whenever I want you around, yeah \r\nAll I go..."
1201,The Beatles,And I Love Her,/b/beatles/and+i+love+her_10026463.html,I give her all my love \r\nThat's all I do \...
1202,The Beatles,And Your Bird Can Sing,/b/beatles/and+your+bird+can+sing_10026364.html,You tell me that you've got everything you wan...

Check the number of Beatles songs in the data set

In [ ]:
data.artist.value_counts().loc[['The Beatles']]

artist
The Beatles    178
Name: count, dtype: int64

Take a look at the first song's lyrics

In [ ]:
beatles.iloc[0,3]

"Well, if your hands start a-clappin'  \r\nAnd your fingers start a-poppin'  \r\nAnd your feet start a-movin' around  \r\nAnd if you start to swing and sway  \r\n  \r\nWhen the band starts to play  \r\nA real cool way out sound  \r\nAnd if you get to can't help it and you can't sit down  \r\nYou feel like you gotta move around  \r\n  \r\nYou get a shot of rhythm and blues.  \r\nWith just a little rock and roll on the side  \r\nJust for good measure.  \r\nGet a pair of dancin' shoes  \r\n  \r\nWell, with your lover by your side  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\n  \r\nAnd chills come up on you  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\n  \r\nGet a shot of rhythm and blues  \r\nWith just a little rock and roll on the side  \r\nJust for good measure  \r\nGet a pair of dancin' shoes  \r\n  \r\nWell, with your lover by your side  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\n  \r\nAnd chills come up on you  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\n  \r\nGet a shot of rhythm and blues  \r\nGet a pair of dancin' shoes  \r\nGet a shot of rhythm and blues  \r\nWell, with your lover by your side  \r\n  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\nAnd chills come up on you  \r\n  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\nWell, here's something for you to do  \r\nWell, here's something for you to do\r\n\r\n"

Remove characters from the lyrics

In [ ]:
import re

newline = lambda x: re.sub('\n', ' ', x) # remove \n
alphanumeric = lambda x: re.sub('\w*\d\w*', ' ', x) # remove alphanumeric words

corpus = beatles.text.map(newline).map(alphanumeric)
corpus.head()

<>:4: SyntaxWarning: invalid escape sequence '\w'
<>:4: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_10497/2279837142.py:4: SyntaxWarning: invalid escape sequence '\w'
  alphanumeric = lambda x: re.sub('\w*\d\w*', ' ', x) # remove alphanumeric words

1198    Well, if your hands start a-clappin'  \r And y...
1199    Words are flowing out like  \r Endless rain in...
1200    Whenever I want you around, yeah  \r All I got...
1201    I give her all my love  \r That's all I do  \r...
1202    You tell me that you've got everything you wan...
Name: text, dtype: object

Create a document term matrix using Count Vectorizer with the stop words turned on to English

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words="english")
X = cv.fit_transform(corpus).toarray()

dt = pd.DataFrame(X, columns=cv.get_feature_names_out()).set_index(beatles.song)
dt.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Across The Universe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
All I've Got To Do,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
And I Love Her,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
And Your Bird Can Sing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Set display options so that the lyrics aren't cut off

In [ ]:
pd.set_option('display.max_colwidth', None)

In [ ]:
beatles[beatles.song=='Imagine'].text

24783    Imagine there's no heaven  \r\nIt's easy if you try  \r\nNo hell below us  \r\nAbove us only sky  \r\nImagine all the people  \r\nLiving for today...  \r\n  \r\nImagine there's no countries  \r\nIt isn't hard to do  \r\nNothing to kill or die for  \r\nAnd no religion too  \r\nImagine all the people  \r\nLiving life in peace...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will be as one  \r\n  \r\nImagine no possessions  \r\nI wonder if you can  \r\nNo need for greed or hunger  \r\nA brotherhood of man  \r\nImagine all the people  \r\nSharing all the world...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will live as one\r\n\r\n
Name: text, dtype: object

Imagine lyrics in Count Vectorizer form

In [ ]:
imagine = list(dt.loc['Imagine'])
imagine[:20]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Define the cosine similarity calculation

In [ ]:
from numpy import dot
from numpy.linalg import norm

cosine = lambda v1, v2: dot(v1, v2) / (norm(v1) * norm(v2))

Calculate all similarities and sort by the most similar

In [ ]:
similarity = [cosine(imagine, song) for song in X]
sorted(list(zip(similarity, beatles.song)), reverse=True)[1:6]

[(np.float64(0.22757944185316942), "I'll Cry Instead"),
 (np.float64(0.1738270040532526), 'In My Life'),
 (np.float64(0.16574838603294895), 'Eleanor Rigby'),
 (np.float64(0.1490280831849844), 'In Spite Of All The Danger'),
 (np.float64(0.14592261028699943), 'All My Loving')]

Create the TF-IDF Vectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(corpus).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(beatles.song)
dt_tfidf.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Across The Universe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
All I've Got To Do,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.120483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And I Love Her,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And Your Bird Can Sing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Calculate all similarities and sort by the most similar using the TF-IDF data

In [ ]:
similarity_tfidf = [cosine(imagine, song) for song in X_tfidf]
sorted(list(zip(similarity_tfidf, beatles.song)), reverse=True)[1:6]

[(np.float64(0.19266277925834221), "I'll Cry Instead"),
 (np.float64(0.18004423848592196), "I'll Get You"),
 (np.float64(0.1551371744116933), 'Eleanor Rigby'),
 (np.float64(0.15054395512050195), 'In My Life'),
 (np.float64(0.12306875209548622), 'Love Of The Loved')]

Compare the lyrics of Imagine and I'll Cry Instead

In [ ]:
# Imagine lyrics
beatles[beatles.song=='Imagine'].text

24783    Imagine there's no heaven  \r\nIt's easy if you try  \r\nNo hell below us  \r\nAbove us only sky  \r\nImagine all the people  \r\nLiving for today...  \r\n  \r\nImagine there's no countries  \r\nIt isn't hard to do  \r\nNothing to kill or die for  \r\nAnd no religion too  \r\nImagine all the people  \r\nLiving life in peace...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will be as one  \r\n  \r\nImagine no possessions  \r\nI wonder if you can  \r\nNo need for greed or hunger  \r\nA brotherhood of man  \r\nImagine all the people  \r\nSharing all the world...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will live as one\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='I\'ll Cry Instead'].text

24774    I've got every reason on earth to be mad  \r\n'Cause I just lost the only girl I had  \r\nIf I could get my way  \r\nI'd get myself locked up today  \r\nBut I can't, so I'll cry instead  \r\n  \r\nI've got a chip on my shoulder that's bigger that my feet  \r\nI can't talk to people that I meet  \r\nIf I could see you now  \r\nI'd try to make you sad somehow  \r\nBut I can't, so I'll cry instead  \r\n  \r\nDon't want to cry when there's people there  \r\nI get shy when they start to stare  \r\nI'm gonna hide myself away  \r\nBut I'll come back again someday  \r\n  \r\nAnd when you do you'd better hide all the girls  \r\nI'm gonna break their hearts all round the world  \r\nYes, I'm gonna break them in two  \r\nAnd show you what your lovin' man can do  \r\nUntil then I'll cry instead\r\n\r\n
Name: text, dtype: object

Compare the two lyrics based on the output

> # The two outputs shows the lyrics of Imagine and I'll Cry Instead. I'll Cry Instead is the most similar song to Imagine as calculated with TF-IDF vectorizer. Both are sad songs, and they almost have the same length. I guess that is their similarity.

Find the two Beatles songs that are the most similar
* Using Count Vectorizer
* Using TF-IDF Vectorizer

Calculate the cosine similarity between all combinations of documents

In [ ]:
from itertools import combinations

pairs = list(combinations(beatles.song.index, 2)) # all song index combos
pairs_0 = list(combinations(range(len(beatles)), 2)) # all index combos starting with (0,1)
song_pairs = [(beatles.song[a_index], beatles.song[b_index]) for (a_index, b_index) in pairs]
song_pairs[:5]

[('A Shot Of Rhythm And Blues', 'Across The Universe'),
 ('A Shot Of Rhythm And Blues', "All I've Got To Do"),
 ('A Shot Of Rhythm And Blues', 'And I Love Her'),
 ('A Shot Of Rhythm And Blues', 'And Your Bird Can Sing'),
 ('A Shot Of Rhythm And Blues', 'Another Girl')]

 Calculate the cosine similarity of the Count Vectorizer document-term matrix

In [ ]:
results = [cosine(X[a_index], X[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.8548876342047523), ('All You Need Is Love', 'Love Me Do')),
 (np.float64(0.8359173188630292),
  ('If I Needed Someone', 'If I Needed Someone To Love')),
 (np.float64(0.8058125835571367), ('And I Love Her', 'Love Me Do')),
 (np.float64(0.7930110315846619), ('If I Fell', 'Love Me Do')),
 (np.float64(0.7478391382739419), ('And I Love Her', 'All You Need Is Love'))]

Calculate the cosine similarity of the TF-IDF Vectorizer document-term matrix

In [ ]:
results = [cosine(X_tfidf[a_index], X_tfidf[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.8717047783261523),
  ('If I Needed Someone', 'If I Needed Someone To Love')),
 (np.float64(0.6599353568343105), ('All You Need Is Love', 'Love Me Do')),
 (np.float64(0.6502842517883831), ('Have A Banana!', 'Crinsk Dee Night')),
 (np.float64(0.6232797327325461), ("Don't Let Me Down", 'Let It Be')),
 (np.float64(0.5275364336322863), ('If I Fell', 'Love Me Do'))]

In [ ]:
beatles[beatles.song=='All You Need Is Love'].text

24695    Love, love, love, love, love, love, love, love, love.  \r\n  \r\nThere's nothing you can do that can't be done.  \r\nNothing you can sing that can't be sung.  \r\nNothing you can say, but you can learn  \r\nHow to play the game  \r\nIt's easy.  \r\nNothing you can make that can't be made.  \r\nNo one you can save that can't be saved.  \r\nNothing you can do, but you can learn  \r\nHow to be you in time  \r\nIt's easy.  \r\n  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\nLove, love, love, love, love, love, love, love, love.  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\n  \r\nThere's nothing you can know that isn't known.  \r\nNothing you can see that isn't shown.  \r\nThere's nowhere you can be that isn't where  \r\nYou're meant to be  \r\nIt's easy.  \r\n  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\nAll you need is love. (All together now).  \r\nAll you need is love. (Everybody).  \r\nAll you need is love, love. Love is all you need.  \r\nLove is all you need.  \r\nLove is all you need  \r\n  \r\n(Yesterday)  \r\n(Oh yeah)  \r\n(She love you, yeah, yeah, yeah)  \r\n(She love you, yeah, yeah, yeah)  \r\n(Oh, yesterday)\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='Love Me Do'].text

24805    Love, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nSomeone to love,  \r\nSomebody new.  \r\nSomeone to love,  \r\nSomeone like you.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\nYeah, love me do.  \r\nWhoa, oh, love me do.\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='If I Needed Someone'].text

24768    If I needed someone to love  \r\nYou're the one that I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nAh, ah, ah, ah  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nAh, ah\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='If I Needed Someone To Love'].text

24769    If I needed someone to love  \r\nYoure the woman I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nIf I needed someone to love  \r\nYoure the woman I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='Have A Banana!'].text

1221    [Speech]  \r\n  \r\nBrian Matthew: Is that it? Is that the end?  \r\nPaul: Yeah, yeah, that's it.  \r\nJohn: Fade, fade!  \r\nBrian: Good track. Oh, well, we'll stop there, stop there, stop there.  \r\nJohn: What an end!  \r\nBrian: Quiet! All right, George.  \r\nJohn: Fade!  \r\nBrian: Hold it!  \r\nGeorge: Oh, thank you.  \r\nJohn: Fade, you silly.  \r\nBrian: Well, we did. We did that. Oh, no! No! We've done that bit!  \r\nJohn: The train comes in now.  \r\nBrian: We did that.  \r\nJohn: Yeah.  \r\nBrian: To pove we weren't playing the record, then, you see. 'Cause,\r\notherwise, there's no point in you being here, is there? Ha, ha, ha!  \r\nJohn: Yeah, we did that, 'cause it sounds just like it, don't it?  \r\nBrian: Pretty cool lot of fellows, aren't you? Here, Ringo, have a banana,\r\ncatch!\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='Crinsk Dee Night'].text

24713    [Speech]  \r\n  \r\nBrian Matthew: The next few minutes, we're in the lap of the gods and the\r\nhands of the Beatles. In my young days, when I was a lad, they used to have\r\nactors in films and now that they--  \r\nPaul: Yes?  \r\nJohn: Hey! Listen!  \r\nPaul: It's all changed, now, Brian. They're not doing that, no actors.  \r\nJohn: It's all changed, now.  \r\nBrian: But this is what I wonder. In those days, the actors used to say their\r\nbest bits were left on the cutting room floor. Did you find that?  \r\nJohn: No, no, no, those were the good bits in the film. You should have seen\r\nthe rest.  \r\nBrian: Yes?  \r\nJohn: Rubbish!  \r\nBrian: Was it, really?  \r\nJohn: Even worse, yes.  \r\nBrian: Who was worst?  \r\nJohn: Oh, Paul.  \r\nBrian: I see.  \r\nPaul: I think John was about the worst.  \r\nJohn: No, it was you.  \r\nPaul: Oh, Ringo was very good. He was. He's a good lad.  \r\nBrian: He was. They're saying he's a new Charlie Chaplin. Do you think that's\r\nright?  \r\nJohn: He was miming.  \r\nPaul: You, too, with Jason.  \r\nJohn: Oh, yes, he's an old one. Okay, Ring?  \r\nBrian: Beginning to look like that. Now, then--  \r\nRingo: All right, John. Can you hear me?  \r\nPaul: Can you hear him? Hello!  \r\nBrian: Not really. I hope not. I hope not!  \r\nJohn: We brought you the flowers, Ring.  \r\nBrian: He's not allowed to talk.  \r\nRingo: Eh?  \r\nJohn: We brought you the flowers.  \r\nRingo: Oh, good.  \r\nJohn: And the grapes.  \r\nRingo: Oh, I like grapes.  \r\nPaul: He likes grapes.  \r\nGeorge: We've been to Portugal.  \r\nBrian: Guess who's, guess who's top of the pops in Portugal, then.  \r\nAll: Who?  \r\nBrian: Los Beatles.  \r\nJohn: Los Beatles? Great, great laugh.  \r\nBrian: I don't suppose you know the title of your film in Portuguese?  \r\nJohn: No. Crinsk dee Night?  \r\nBrian: Could be. Let's hear the number, shall we?  \r\nJohn: Right\r\n\r\n
Name: text, dtype: object

Compare the results. Which Vectorizer seems to do a better job?

> # I don't know how to distinguish which vectorizer did a better job, all I can see is that both of them have 3 similar songs in their top 5.

## Supplementary Activity

* Use a dataset that consists of text document
* Remove special characters
* Compare the similar document using Count Vector and TF-IDF Vectorizer
* Use the cosine similarity to measure the similarity of text

In [ ]:
#type your code here
from numpy import dot
from numpy.linalg import norm
import pandas as pd
import re

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.tag import pos_tag
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

#### Importing dataset

I obtained my dataset here:

> https://www.kaggle.com/datasets/jrobischon/wikipedia-movie-plots

In [ ]:
# Use a dataset that consists of text document
# Had to limit dataset to only 10k because session will crash

movies = pd.read_csv('/content/wiki_movie_plots_deduped.csv')[['Title', 'Plot']].head(10000).drop_duplicates(subset=['Title'])
movies.head()

,Title,Plot
0,Kansas Saloon Smashers,"A bartender is working at a saloon, serving dr..."
1,Love by the Light of the Moon,"The moon, painted with a smiling face hangs ov..."
2,The Martyred Presidents,"The film, just over a minute long, is composed..."
3,"Terrible Teddy, the Grizzly King",Lasting just 61 seconds and consisting of two ...
4,Jack and the Beanstalk,The earliest known adaptation of the classic f...

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9623 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   9623 non-null   object
 1   Plot    9623 non-null   object
dtypes: object(2)
memory usage: 225.5+ KB

#### Tokenization for the discussion

In [ ]:
# tokenize words

movies['Plot_tknz'] = movies.Plot.map(word_tokenize)
movies.head()

,Title,Plot,Plot_tknz
0,Kansas Saloon Smashers,"A bartender is working at a saloon, serving dr...","[A, bartender, is, working, at, a, saloon, ,, ..."
1,Love by the Light of the Moon,"The moon, painted with a smiling face hangs ov...","[The, moon, ,, painted, with, a, smiling, face..."
2,The Martyred Presidents,"The film, just over a minute long, is composed...","[The, film, ,, just, over, a, minute, long, ,,..."
3,"Terrible Teddy, the Grizzly King",Lasting just 61 seconds and consisting of two ...,"[Lasting, just, 61, seconds, and, consisting, ..."
4,Jack and the Beanstalk,The earliest known adaptation of the classic f...,"[The, earliest, known, adaptation, of, the, cl..."

In [ ]:
# Tokenize (words with remove special characters and numbers)

remove_special = lambda x: re.sub(r'[!?]' ,' ', x)
remove_number = lambda x: re.sub(r'[/d!?]' ,' ', x)

movies['Plot_tknz'] = movies.Plot.map(remove_special).map(remove_number).map(word_tokenize)
movies.head()

,Title,Plot,Plot_tknz
0,Kansas Saloon Smashers,"A bartender is working at a saloon, serving dr...","[A, barten, er, is, working, at, a, saloon, ,,..."
1,Love by the Light of the Moon,"The moon, painted with a smiling face hangs ov...","[The, moon, ,, painte, with, a, smiling, face,..."
2,The Martyred Presidents,"The film, just over a minute long, is composed...","[The, film, ,, just, over, a, minute, long, ,,..."
3,"Terrible Teddy, the Grizzly King",Lasting just 61 seconds and consisting of two ...,"[Lasting, just, 61, secon, s, an, consisting, ..."
4,Jack and the Beanstalk,The earliest known adaptation of the classic f...,"[The, earliest, known, a, aptation, of, the, c..."

In [ ]:
# Tokenize (words with remove punctuation and all lowercase)

remove_punc = lambda x: re.sub(r'[!?]' ,' ', x.lower())
remove_number = lambda x: re.sub(r'[/d!?]' ,' ', x.lower())

movies['Plot_tknz'] = movies.Plot.map(remove_special).map(remove_number).map(word_tokenize)
movies.head()

,Title,Plot,Plot_tknz
0,Kansas Saloon Smashers,"A bartender is working at a saloon, serving dr...","[a, barten, er, is, working, at, a, saloon, ,,..."
1,Love by the Light of the Moon,"The moon, painted with a smiling face hangs ov...","[the, moon, ,, painte, with, a, smiling, face,..."
2,The Martyred Presidents,"The film, just over a minute long, is composed...","[the, film, ,, just, over, a, minute, long, ,,..."
3,"Terrible Teddy, the Grizzly King",Lasting just 61 seconds and consisting of two ...,"[lasting, just, 61, secon, s, an, consisting, ..."
4,Jack and the Beanstalk,The earliest known adaptation of the classic f...,"[the, earliest, known, a, aptation, of, the, c..."

In [ ]:
# Tokenize (words with remove punctuation, all lowercase and remove stop words)

stop_words = lambda x: [y for y in x if y not in stopwords.words('english')]

movies['Plot_tknz'] = movies.Plot_tknz.apply(stop_words)
movies.head()

,Title,Plot,Plot_tknz
0,Kansas Saloon Smashers,"A bartender is working at a saloon, serving dr...","[barten, er, working, saloon, ,, serving, rink..."
1,Love by the Light of the Moon,"The moon, painted with a smiling face hangs ov...","[moon, ,, painte, smiling, face, hangs, park, ..."
2,The Martyred Presidents,"The film, just over a minute long, is composed...","[film, ,, minute, long, ,, compose, two, shots..."
3,"Terrible Teddy, the Grizzly King",Lasting just 61 seconds and consisting of two ...,"[lasting, 61, secon, consisting, two, shots, ,..."
4,Jack and the Beanstalk,The earliest known adaptation of the classic f...,"[earliest, known, aptation, classic, fairytale..."

In [ ]:
# Tokenize (words with remove punctuation, all lowercase and remove stop words, with speech_tagging)

speech_tag = lambda x: nltk.pos_tag(x)

movies['Plot_tknz_tag'] = movies.Plot_tknz.apply(speech_tag)
movies.head()

,Title,Plot,Plot_tknz,Plot_tknz_tag
0,Kansas Saloon Smashers,"A bartender is working at a saloon, serving dr...","[barten, er, working, saloon, ,, serving, rink...","[(barten, RB), (er, JJ), (working, VBG), (salo..."
1,Love by the Light of the Moon,"The moon, painted with a smiling face hangs ov...","[moon, ,, painte, smiling, face, hangs, park, ...","[(moon, NN), (,, ,), (painte, NN), (smiling, V..."
2,The Martyred Presidents,"The film, just over a minute long, is composed...","[film, ,, minute, long, ,, compose, two, shots...","[(film, NN), (,, ,), (minute, NN), (long, RB),..."
3,"Terrible Teddy, the Grizzly King",Lasting just 61 seconds and consisting of two ...,"[lasting, 61, secon, consisting, two, shots, ,...","[(lasting, VBG), (61, CD), (secon, JJ), (consi..."
4,Jack and the Beanstalk,The earliest known adaptation of the classic f...,"[earliest, known, aptation, classic, fairytale...","[(earliest, JJS), (known, VBN), (aptation, NN)..."

#### Remove special characters

In [ ]:
# Now, I will apply of the process that was made

newline = lambda x: re.sub('\n', ' ', x)
remove_punc = lambda x: re.sub(r'[!?]' ,' ', x.lower())
remove_number = lambda x: re.sub(r'[/d!?]' ,' ', x.lower())

testing = movies.Plot.map(newline).map(remove_punc).map(remove_number)
testing.head()

0    a barten er is working at a saloon, serving  r...
1    the moon, painte  with a smiling face hangs ov...
2    the film, just over a minute long, is compose ...
3    lasting just 61 secon s an  consisting of two ...
4    the earliest known a aptation of the classic f...
Name: Plot, dtype: object

#### Compare the similar document using Count Vector

In [ ]:
# Count vectorizer

cv = CountVectorizer(stop_words="english")
X = cv.fit_transform(testing).toarray()

plot_cv = pd.DataFrame(X, columns=cv.get_feature_names_out()).set_index(movies.Title)

In [ ]:
# Let's find out what movies have "similar" plot to Huckleberry Finn
# I use cosine to calculate the distance

cosine = lambda v1, v2: dot(v1, v2) / (norm(v1) * norm(v2))

movie_hf = list(plot_cv.loc['Huckleberry Finn'])
similarity = [cosine(movie_hf, plot) for plot in X]

In [ ]:
# 5 Movies with most similar plots

sorted(list(zip(similarity, movies.Title)), reverse=True)[1:6]

[(np.float64(0.4005319130248491), 'Tom Sawyer'),
 (np.float64(0.33731814917823855), 'Bad for Each Other'),
 (np.float64(0.30942637387763805), 'The Adventures of Huckleberry Finn'),
 (np.float64(0.2830664467807362), 'The Public Enemy'),
 (np.float64(0.27924109741731806), 'Hell Drivers')]

#### Compare the similar document using TF-IDF Vectorizer

In [ ]:
# TF-IDF Vectorizer

tf = TfidfVectorizer(stop_words="english")
y = tf.fit_transform(testing).toarray()

plot_tf = pd.DataFrame(y, columns=tf.get_feature_names_out()).set_index(movies.Title)

In [ ]:
# Let's find out what movies have "similar" plot to Huckleberry Finn

movie_hf = list(plot_tf.loc['Huckleberry Finn'])

similarity = [cosine(movie_hf, plot) for plot in X]

In [ ]:
# 5 Movies with most similar plots

sorted(list(zip(similarity, movies.Title)), reverse=True)[1:6]

[(np.float64(0.42938259233003484), 'Tom Sawyer'),
 (np.float64(0.4142116004198), 'Roberta'),
 (np.float64(0.38489752307367137), 'The Adventures of Huckleberry Finn'),
 (np.float64(0.30282790533120013), 'Huck and Tom'),
 (np.float64(0.17055110863467682), 'Bad for Each Other')]

> ***As seen in the results, both have the same top 1 and top 3 (not really a different movie), but the rest don't match.***

#### Comparison of top similar to the main movie

In [ ]:
pd.set_option('display.max_colwidth', None)

In [ ]:
movies[movies.Title=='Huckleberry Finn'].Plot

327    As described in a film publication,[2] Huckleberry Finn (Sargent) has been adopted by the Widow Douglas (K. Griffith) who plans to "civilize" him. With Tom Sawyer (G. Griffith) he forms a robber gang, and in a cave has the local boys take an oath to stick together. In his bedroom he runs into his no-account father (Lanning) who steals Huck's small change and later kidnaps Huck, taking him in a small boat down the river, while Tom and the gang wait for their leader to appear. Huck later escapes from a cabin where his father mistreated him, making it look as if he drowned while getting away in a canoe.\r\nRumors of Huck's death spreads. Jim (Reed), the widow's slave boy, hears that he is to be sold and runs off, and joins Huck on a raft. Duke (Humphrey) and King (Bates), two broken-down actors fleeing a crowd they had fooled with a mock theatrical performance, join them. At the next town the actors again fool the people with a pretend theatrical performance with Huck acting as the doorkeeper. Further downstream the actors then impersonate the brothers of a deceased man named Wilks in an attempt to obtain the inheritance, but Huck takes the money to keep it from the actors after he is smitten by the daughter, Mary Jane Wilks (Ralston). Huck and Jim leave to escape the wrath of their former companions just as the actual relatives of the dead man show up.\r\nAfter peace is made when King and Duke rejoin the group, a shabby trick is performed when King sells Jim to a man named Phelps and then tells Huck that Jim has been lost. Upon learning the truth, Huck sets out to rescue his friend. He discovers that Mrs. Phelps (Moore) is the sister of Tom's Aunt Polly. Huck poses as the nephew Tom, whom Mrs. Phelps has never met. Then the real Tom arrives, who is surprised as he believed that Huck had died. After exchanging signals, Tom poses as his brother Sid and they go through with a plan. In a struggle to get Jim away, Tom is shot in the leg. Jim escapes, and while the two youngsters are congratulating themselves at Tom's sickbed, Aunt Polly arrives and says that Jim had been freed a month earlier. She informs the Phelps of Huck's actual identity and takes him back, cured of his wandering, to the Widow Douglas.
Name: Plot, dtype: object

In [ ]:
movies[movies.Title=='Tom Sawyer'].Plot

1039    After arguing with his sweetheart, Becky Thatcher, Tom Sawyer seeks solace from his friend Huck Finn, who tells him about a mysterious cure for warts that requires them to visit the local cemetery at midnight. While there they witness a murder committed by Injun Joe, who convinces Muff Potter, who also was there but in an inebriated state, that he is guilty of the crime. Tom and Huck promise each other they will not divulge what they have seen.\r\nWhen Tom is caught lying about stealing his half-brother Sid's crabapples, his Aunt Polly punishes him by making him whitewash the fence on a Saturday morning. The boy leads his friends to believe he is enjoying the task, and before long they are giving him their treasures in exchange for the privilege of joining in the fun.\r\nTogether with Huck and Joe Harper, Tom runs away from home to become a pirate. The three set off on a raft to Jacksons Island in the Mississippi River, where they remain for three days. Upon returning home, Tom discovers it was thought the three had drowned, and the boys attend their own funeral service at the church.\r\nAt Muff Potter's trial, Tom admits the truth about the murder, but Injun Joe manages to escape. While attending the school picnic near a cavern, Tom and Becky decide to explore it and get lost. As they try to find their way out, they stumble upon Injun Joe and a chest of gold. While angrily pursuing the two children, he falls into a crevasse and is killed. Huck finds Tom and Becky and leads them to safety, together with the treasure.
Name: Plot, dtype: object

> ***As we know, these two stories are connected to each other. Perhaps this is just a coincidence, but it is amazing that both vectorizers can see it.***

#### Comparison of other top similar movies that are different in both vectorizer

In [ ]:
movies[movies.Title=='The Public Enemy'].Plot

1185    As youngsters in 1900s Chicago, Tom Powers (James Cagney) and his lifelong friend Matt Doyle (Edward Woods) engage in petty theft, selling their loot to "Putty Nose" (Murray Kinnell). Putty Nose persuades them to join his gang on a fur warehouse robbery, assuring them he will take care of them if anything goes wrong. When Tom is startled by a stuffed bear, he shoots it, alerting the police, who kill gang member Larry Dalton. Chased by a cop, Tom and Matt have to gun him down. However, when they go to Putty Nose for help, they find he has left town.\r\nTom's straightlaced older brother Mike (Donald Cook) tries, but fails, to talk Tom into giving up crime. Tom keeps his activities secret from his doting mother (Beryl Mercer). When America enters World War I in 1917, Mike enlists in the Marines.\r\nIn 1920, with Prohibition about to go into effect, Paddy Ryan (Robert Emmett O'Connor) recruits Tom and Matt as beer "salesmen" (enforcers) in his bootlegging business. He allies himself with noted gangster Samuel "Nails" Nathan (Leslie Fenton). As the bootlegging business becomes ever more lucrative, Tom and Matt flaunt their wealth.\r\nMike finds out that his brother's money comes not from politics, as Tom claims, but from bootlegging, and declares that Tom's success is based on nothing more than "beer and blood" (the title of the book upon which the film is based). Tom retorts in disgust: "Your hands ain't so clean. You killed and liked it. You didn't get them medals for holding hands with them Germans."\r\nTom and Matt acquire girlfriends, Kitty (an uncredited Mae Clarke) and Mamie (Joan Blondell) respectively. Tom eventually tires of Kitty; in a famous scene, when she complains once too often, he angrily pushes half a grapefruit into her face. He then drops her for Gwen Allen (Jean Harlow), a woman with a self-confessed weakness for bad men. At a restaurant on the night of Matt's wedding reception to Mamie, Tom and Matt recognize Putty Nose and follow him home. Begging for his life, Putty plays a song on the piano that he had entertained Tom and Matt with when they were kids. Tom shoots him in the back.\r\nTom gives his mother a large wad of money, but Mike rejects the gift. Tom tears up the banknotes and throws them in his brother's face. "Nails" Nathan dies in a horse riding accident, prompting Tom to find the horse and shoot it. A rival gang headed by "Schemer" Burns takes advantage of the disarray resulting from Nathan's death, precipitating a gang war.\r\nLater, Matt is gunned down in public, with Tom narrowly escaping the same fate. Furious, Tom takes it upon himself to single-handedly settle scores with Burns and some of his men. Tom is seriously wounded in the shootout, and ends up in the hospital. When his mother, brother, and Matt's sister Molly come to see him, he reconciles with Mike and agrees to reform. However, Paddy warns Mike that Tom has been kidnapped by the Burns mob from the hospital. Later, his dead body is returned to the Powers home.
Name: Plot, dtype: object

In [ ]:
movies[movies.Title=='Hell Drivers'].Plot

6796    "Joe Yately" (Stanley Baker), whom everyone calls "Tom", has just been released from prison and is determined to start a new life. Tom arrives at Hawletts, a contractor which transports loads of gravel (“ballast”) from a nearby quarry, and tells gatekeeper Harry that he is looking for work. Harry lets him in and sends him to Mr. Cartley, the manager.\r\nTom tells Lucy (Cartley's secretary) that he met "Leggy" Legubin, a former Hawletts driver who had an accident resulting in a plate in his skull and told Tom that Hawletts paid its drivers well. Legubin's accident made Tom think there was a job available. Lucy recommends him to Cartley, who hires him for a trial run. Cartley tells Tom that his drivers transport their 10-ton loads fast, over bad roads. Speeding tickets and repairs are covered by the drivers. Hawletts has a bonus system in which the drivers receive seven shillings a load and four shillings an hour, with an additional weekly bonus for the cleanest truck. They are expected to deliver a minimum of twelve loads a day; if a driver falls behind, he is fired. Each run is 20 miles (32 km) round-trip; according to Cartley, one driver makes eighteen runs a day.\r\nTom goes on a trial run with Ed, the mechanic, who is impressed with his driving skill but appears noncommittal. During the trial run, the brakes on his faulty truck, # 13, temporarily go out. Cartley hires him. Tom is accepted by all the other drivers except Red (Patrick McGoohan), an Irish foreman and head driver who is a violent bully. Tom befriends Gino (Herbert Lom), an Italian driver who is in love with Lucy. Red offers a £250 gold cigarette case to any driver who can make more runs than he does in a day, and Tom is determined to try. However, he learns that Red has kept his place at the top by taking a very risky short cut through a quarry which none of the other drivers will do.\r\nOne evening, the drivers go to a dance at a nearby hall and start a fight. When the police are called Tom flees the scene, fearful that his criminal record will return him to prison. Red calls Tom a coward and the other drivers (except Gino) turn on him, bullying him incessantly.\r\nLucy and Tom are attracted to each other, but Tom hesitates out of loyalty to Gino. The other drivers continue picking on him but, determined to escape his criminal past, he does not fight back. Tom learns that Cartley and Red have been scamming money by hiring fewer drivers than the budget allows and pocketing the difference, forcing the drivers to haul extra loads at high speed. Tom confronts Red and defeats him in a fistfight. Gino offers to switch truck numbers with Tom the next day, so that the others can harass him instead of Tom for a change, to help Tom to win the gold cigarette case. That night, Lucy breaks up with Gino, who has asked her to marry him and learns that she loves Tom. Despite his heartbreak, Gino switches numbers as arranged and uses Tom's number 13 the next day, without realising that Tom has left and is about to catch a train for London and go back to his life of crime. Whilst waiting for his train, Lucy rushes into the waiting room and tells him that Gino has been seriously injured in a crash. Distraught, they rush to his hospital bedside where he is dying. He tells Tom, "I threw them off like we planned, for you to win. Crazy. You don't even come." Tom asks him if it was Red, and with his dying breath, Gino tries to say "Red."\r\nTom returns to the depot and confronts Cartley. He tells him that Gino has died and he knows why, and that he knows about the scam. Cartley offers Tom a deal whereby they can share the extra money, and Tom can take Red's place in Truck 1. Tom is having none of it, but jumps into Truck 1 anyway and drives off. When Red turns up he forces Cartley to join him in Tom's faulty truck # 13, disguised at truck # 3, and they give chase. Red correctly guesses that Tom will take the dangerous short cut through the quarry, and they lie in wait there in order to catch Tom on his return journey. When Tom appears with his truck full of ballast, Red gives chase and side swipes Tom's truck many times, finally forcing it off the road and onto the edge of the quarry where it dangles precariously, with Tom unconscious inside. But now the brakes on Red's truck (# 13) fail, he loses control, goes over the side and he and Cartley are killed when it explodes in a fireball. Tom wakes up and escapes, just in time before his own truck tumbles down into the quarry, and Lucy (who followed them in a Hawletts jeep) runs to him.
Name: Plot, dtype: object

In [ ]:
movies[movies.Title=='Roberta'].Plot

1976    John Kent (Randolph Scott), a former star football player at Harvard, goes to Paris with his friend Huck Haines (Fred Astaire) and the latter's dance band, the Wabash Indianians. Alexander Voyda (Luis Alberni) has booked the band, but refuses to let them play when he finds the musicians are not the Indians he expected, but merely from Indiana (Huck Haines and his Indianians Band).\r\nJohn turns to the only person he knows in Paris for help, his Aunt Minnie (Helen Westley), who owns the fashionable "Roberta" gown shop. While there, he meets her chief assistant (and secretly the head designer), Stephanie (Irene Dunne). John is quickly smitten with her.\r\nMeanwhile, Huck unexpectedly stumbles upon someone he knows very well. "Countess Scharwenka", a temperamental customer at Roberta's, turns out to be his hometown sweetheart Lizzie Gatz (Ginger Rogers). She gets Huck's band an engagement at the nightclub where she is a featured entertainer, and Huck agrees to keep her true identity a secret.\r\nTwo things trouble John. One is Ladislaw (Victor Varconi), the handsome Russian deposed prince and doorman who seems too interested in Stephanie. The other is the memory of Sophie (Claire Dodd), the snobbish, conceited girlfriend he left behind after a quarrel over his lack of sophistication and polish.\r\nWhen Aunt Minnie dies unexpectedly without leaving a will, John inherits the shop. Knowing nothing about women's fashion and aware that his aunt intended for Stephanie to inherit the business, he persuades Stephanie to remain as his partner. Correspondents flock to hear what a football player has to say about feminine fashions. Huck gives the answers, making a lot of weird statements about the innovations John is planning to introduce.\r\nSophie arrives in Paris, attracted by John's good fortune. She enters the shop, looking for a dress, but is dissatisfied with everything Stephanie shows her. Huck persuades her to choose a gown that John had ordered to be discarded as too vulgar. When John sees her in it, they quarrel for the final time.\r\nJohn reproaches Stephanie for selling Sophie the gown. Terribly hurt, Stephanie quits the shop. With Roberta's putting on a fashion show in a week, Huck takes over the design work, with predictably bad results. When Stephanie sees his awful creations, she is persuaded to return to save Roberta's reputation.\r\nThe show is a triumph, helped by the entertainment provided by Huck, Countess Scharwenka, and the band. (A pre-stardom Lucille Ball, with platinum blond hair, appears uncredited in her first RKO film[3] as a model wearing an elaborate feather cape, after the vocal by Dunne, in the fashion show.[4]) The closing sensation is a gown modeled by Stephanie herself. At the show, John overhears that she and Ladislaw are leaving Paris and mistakenly assumes that they have married. Later, he congratulates her for becoming a princess. When she informs him that Ladislaw is merely her cousin and that the title has been hers since birth, the lovers are reunited. Huck and Lizzie, who decide to get married, do a final tap dance sequel.
Name: Plot, dtype: object

In [ ]:
movies[movies.Title=='Huck and Tom'].Plot

221    As described in a film magazine,[3] while in a graveyard trying an old remedy to get rid of their warts, Tom (Pickford) and Huck (Gordon) witness a murder. At the trial their repetition of the story clears Muff Potter (Bates), an innocent suspect and victim of Injun Joe's (Lanning) plot. Injun Joe escapes to the Painted Cave, where the next day Tom and Becky (Horton) become lost. After a four-day search the missing ones come home and the entrance to the Painted Cave is sealed. Tom tells Judge Thatcher (Burton) that Injun Joe is hiding there. The entrance to the cave is opened and the dead body of the murderer is brought out. Tom and Huck become the possessors of a treasure they found, and with this fortune they plan on becoming great and fierce robbers.
Name: Plot, dtype: object

## Conclusion

> ***In this activity, I was abble to demonstrate some strings manipulation with tokenization and how we can "clean" them by removing special characters using RE library. In this activity, we are essentially measuring text similarities using distance. To calculate the distance, I used cosine but we can use other measurements such as Manhattan and Euclidean. To find the similarity, we used vectorized every words such that they became individual features, kind of like one-hot encoding. I demonstrated two vectorizers in this activity: Count Vector and TF-IDF. Both of these vectorizers have common results but there are some differences. Overall, I was able to implement text similarity with vectorizers.***